name: condabuild
on:
  workflow_dispatch:
  schedule:
    - cron: "46 4/16 * * *"

env:
  ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  FASTCHAN: ${{ secrets.ANACONDA_TOKEN }}

jobs:
  build:
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        py:  [3.7, 3.8, 3.9, "3.10"]
        os:  [ubuntu, windows, macos]
        nm: [opencv-python-headless, sentencepiece]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.py }}
          channels: fastai,defaults,conda-forge
          miniforge-version: latest
          #auto-update-conda: false
          miniforge-variant: Mambaforge
      - name: install deps
        run: |
          #conda install -yq libiconv
          #conda install -yq mamba
          mamba install -yq -vv boa anaconda-client conda-build ghapi nbdev 
      - name: build
        run: python -vv build.py --pypinm ${{ matrix.nm }}
